### PR TITLE
Add Implementation/responsiveness design for home page and about page

### PR DESCRIPTION
**Pull request by xuezzou**
- Index page + about page  

1. Fixed background image (both desktop and mobile) such that it won’t change as we scroll down (mostly did it through global.css)
2. Increased the size of V background to match Kathy's design
3. Un-fixed footer on bottom to match the design
4. Added small padding under the footer section and added big padding under the index page to match the design 
5. Changed the grid layout such that it displayed things correctly
6. Added a small slidein animation for about page content
6. (nit) Changed the text component of Next Hackathon

### CODE REVIEW

**Comment by xuezzou** [comment]
@SamLee514 @BaibhaVatsa

**Review by SamLee514 — APPROVED** [review]
Looks good!

**Comment by SamLee514** [comment]
@xuezzou hm actually, it looks like adding Padding to the home page makes most of the links unclickable in the footer.

**Comment by xuezzou** [comment]
@SamLee514 Tried to fix the position of header on scroll and also change the grid layout based on that ~

**Comment by xuezzou** [comment]
TODO: the scroll up animation looks really weird on the deployment, need to fix that

**Pull request merged**
